spring:
#  org.springframework.boot.autoconfigure.context.MessageSourceProperties
  messages:
    basename: il8n/messages
    encoding: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: conditions